
default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: find_my_sup_development
test:
  <<: *default
  database: find_my_sup_test

production:
  <<: *default
  database: find_my_sup_production
  username: find_my_sup
  password: <%= ENV['FIND_MY_SUP_DATABASE_PASSWORD'] %>
